export const demoEmails = [
  {
    id: "demo-email-bci-logistics", threadId: "thread-bci-event", senderName: "Event Organizer", senderEmail: "events@futureinterfaces.org",
    subject: "Final details for today’s BCI presentation", receivedHoursAgo: 1,
    body: "Your session, The Future of Non-Invasive Brain-Computer Interfaces, is confirmed for 2:30 PM today in Harbor Room B. Please arrive by 1:55 PM rather than 2:10 so the AV team can test the wireless microphone and presentation adapter. Check in at the second-floor speaker desk and bring a local copy of your slides in case the venue network is slow.",
    shortSummary: "The BCI presentation is at 2:30 PM in Harbor Room B, and speaker check-in moved earlier to 1:55 PM for an AV test.",
    importance: 10, urgency: 10, category: "presentation", requiresResponse: false, suggestedAction: "Review the updated logistics before arrival.",
    deadlineHoursFromNow: 3, relatedMeetingId: "meeting-bci-presentation", relatedPresentationId: "demo-bci-presentation", isRead: false, isArchived: false,
  },
  {
    id: "demo-email-manager-input", threadId: "thread-project-review", senderName: "Jordan Lee", senderEmail: "jordan.lee@northstar.example",
    subject: "Need your input before today’s project review", receivedHoursAgo: 2,
    body: "Before our 1 PM project review, I need your recommendation on the pilot rollout. Option A launches to all three design partners next Monday. Option B starts with one partner for two weeks and expands after we validate support volume. Please reply before noon with A or B and one sentence on the main risk you want tracked. My recommendation is B because it gives us a cleaner feedback loop.",
    shortSummary: "Jordan needs a recommendation on a broad or phased pilot rollout before noon, ahead of the 1 PM review.",
    importance: 9, urgency: 9, category: "work", requiresResponse: true, suggestedAction: "Reply before noon with option A or B and the primary risk to track.",
    deadlineHoursFromNow: 1, relatedMeetingId: "meeting-project-review", relatedPresentationId: null, isRead: false, isArchived: false,
  },
  {
    id: "demo-email-maya-followup", threadId: "thread-partnership-followup", senderName: "Maya Chen", senderEmail: "maya.chen@brightlabs.example",
    subject: "Follow-up and next steps from yesterday", receivedHoursAgo: 5,
    body: "Thanks again for yesterday’s conversation. We agreed on three next steps: I will share the revised research brief, your team will identify one technical reviewer, and we will hold a forty-five minute working session next week. Could you confirm today whether Tuesday at 10 AM works for that session? If not, Thursday at 3 PM is also open.",
    shortSummary: "Maya summarized three partnership next steps and needs confirmation today for Tuesday at 10 AM or Thursday at 3 PM.",
    importance: 8, urgency: 7, category: "follow_up", requiresResponse: true, suggestedAction: "Confirm one of the proposed working-session times today.",
    deadlineHoursFromNow: 8, relatedMeetingId: "meeting-partnership-working-session", relatedPresentationId: null, isRead: true, isArchived: false,
  },
  {
    id: "demo-email-recruiter", threadId: "thread-recruiter", senderName: "Alex Morgan", senderEmail: "alex.morgan@talentsearch.example",
    subject: "Interview availability next week", receivedHoursAgo: 7,
    body: "The product innovation team enjoyed reviewing your background and would like to schedule a thirty-minute introductory interview next week. We currently have Monday at 11 AM, Tuesday at 2 PM, or Thursday at 9:30 AM Pacific available. Let me know which option works, or send two alternatives.",
    shortSummary: "Recruiter Alex Morgan offered three thirty-minute interview times next week.",
    importance: 6, urgency: 4, category: "recruiting", requiresResponse: true, suggestedAction: "Reply with a preferred interview time by tomorrow.",
    deadlineHoursFromNow: 30, relatedMeetingId: null, relatedPresentationId: null, isRead: false, isArchived: false,
  },
  {
    id: "demo-email-bird-course", threadId: "thread-learning-platform", senderName: "Learning Platform", senderEmail: "lessons@learning.example",
    subject: "Your next lesson is ready", receivedHoursAgo: 10,
    body: "Your next lesson in Introduction to Bird Behavior and Neuroscience is ready. Magnetic Navigation in Migratory Birds explores how birds may use light-sensitive proteins and magnetic information during long journeys. The audio lesson takes about eight minutes and can be continued from your commute playlist.",
    shortSummary: "The eight-minute magnetic-navigation lesson in the bird course is ready.",
    importance: 5, urgency: 2, category: "learning", requiresResponse: false, suggestedAction: "Listen when there is an eight-minute learning window.",
    deadlineHoursFromNow: null, relatedMeetingId: null, relatedPresentationId: null, isRead: false, isArchived: false,
  },
  {
    id: "demo-email-tech-newsletter", threadId: "thread-tech-brief", senderName: "Tech Brief Daily", senderEmail: "digest@techbrief.example",
    subject: "Today in AI and emerging technology", receivedHoursAgo: 3,
    body: "Today’s headlines: new efficiency benchmarks for small language models, a proposed framework for neural-data privacy, robotics funding updates, and five product launches from the developer tools ecosystem. Open the full edition for analysis and links.",
    shortSummary: "A daily technology newsletter covering AI efficiency, neural privacy, robotics funding, and product launches.",
    importance: 3, urgency: 1, category: "newsletter", requiresResponse: false, suggestedAction: "Read later.",
    deadlineHoursFromNow: null, relatedMeetingId: null, relatedPresentationId: null, isRead: false, isArchived: false,
  },
  {
    id: "demo-email-coffee-receipt", threadId: "thread-coffee-receipt", senderName: "Coffee Shop", senderEmail: "receipts@harborcoffee.example",
    subject: "Your receipt", receivedHoursAgo: 1,
    body: "Thanks for visiting Harbor Coffee. One oat milk latte, six dollars and twenty-five cents, paid by card. This message is your electronic receipt.",
    shortSummary: "A six-dollar-and-twenty-five-cent coffee receipt.",
    importance: 1, urgency: 1, category: "receipt", requiresResponse: false, suggestedAction: "No action needed.",
    deadlineHoursFromNow: null, relatedMeetingId: null, relatedPresentationId: null, isRead: true, isArchived: false,
  },
  {
    id: "demo-email-priya-networking", threadId: "thread-priya-networking", senderName: "Priya Shah", senderEmail: "priya@neurodesign.example",
    subject: "Great meeting you yesterday", receivedHoursAgo: 18,
    body: "It was great meeting you after the accessibility panel. Your point about designing neural interfaces around user agency stayed with me. Here is the inclusive research toolkit I mentioned. I would also be happy to introduce you to Elena Ruiz, who leads assistive input research at Open Access Lab, if that would be useful.",
    shortSummary: "Priya shared an inclusive-research resource and offered an introduction to an assistive-input researcher.",
    importance: 7, urgency: 3, category: "networking", requiresResponse: true, suggestedAction: "Thank Priya and accept the introduction later today or tomorrow.",
    deadlineHoursFromNow: 36, relatedMeetingId: null, relatedPresentationId: null, isRead: true, isArchived: false,
  },
  {
    id: "demo-email-team-approval", threadId: "thread-demo-approval", senderName: "Demo Project Team", senderEmail: "team@commutecopilot.example",
    subject: "Quick approval needed before 4 PM", receivedHoursAgo: 0.5,
    body: "We need your approval to use the new route-animation build in today’s demo. It fixes the destination transition but has not completed the full tablet regression. Please reply approve or hold before 4 PM. If we do not hear back, the team will keep the older build and the smoother route transition will not be included.",
    shortSummary: "The demo team needs approval before 4 PM to use the improved route-animation build; otherwise it will keep the older build.",
    importance: 9, urgency: 10, category: "approval", requiresResponse: true, suggestedAction: "Reply approve or hold before 4 PM.",
    deadlineHoursFromNow: 5, relatedMeetingId: "meeting-hackathon-demo", relatedPresentationId: null, isRead: false, isArchived: false,
  },
  {
    id: "demo-email-personal-dinner", threadId: "thread-dinner", senderName: "Sam Rivera", senderEmail: "sam.rivera@example.net",
    subject: "Dinner this weekend?", receivedHoursAgo: 20,
    body: "A few of us are thinking about dinner Saturday around seven. No firm reservation yet. Let me know by Friday if you want me to include you in the headcount.",
    shortSummary: "Sam is organizing a casual Saturday dinner and wants a headcount by Friday.",
    importance: 3, urgency: 2, category: "personal", requiresResponse: true, suggestedAction: "Reply by Friday if interested.",
    deadlineHoursFromNow: 48, relatedMeetingId: null, relatedPresentationId: null, isRead: false, isArchived: false,
  },
];
