export const demoPresentation = {
  id: "demo-bci-presentation",
  userId: "demo-user",
  title: "The Future of Non-Invasive Brain-Computer Interfaces",
  audience: "Technology leaders, researchers, and product strategists",
  durationMinutes: 20,
  objective: "Explain why non-invasive brain-computer interfaces are becoming practical and propose a responsible path from research to useful products.",
  mainThesis: "Non-invasive BCIs will create meaningful near-term value by augmenting communication and control in focused contexts, provided that signal limits, privacy, and user agency shape product design from the beginning.",
  openingScript: "Imagine being able to select a letter, control a cursor, or communicate a simple intention without moving a muscle. That possibility is no longer limited to implanted devices or science fiction. Today I want to show you how non-invasive brain-computer interfaces are improving, where they can create real value, and why responsible design will determine whether people trust them.",
  closingScript: "The future of non-invasive BCI is not mind reading. It is carefully designed assistance: translating limited, intentional neural signals into useful actions. If we focus on real human needs, honest capability claims, privacy, and user control, this technology can expand access without asking people to surrender agency.",
  estimatedPrepTimeMinutes: 30,
  slides: [
    {
      id: "demo-bci-slide-1", slideNumber: 1, title: "A New Input Channel", purpose: "Open with a concrete human benefit and define the talk's scope.",
      keyPoints: ["BCIs translate measured brain activity into commands", "Non-invasive systems measure signals without surgery", "The near-term goal is useful assistance, not unrestricted mind reading"],
      speakerNotes: "Begin with the communication example from the opening. Define a BCI in one sentence. Emphasize that this talk focuses on non-invasive sensing such as EEG and related optical or wearable approaches. Set expectations early: current systems infer constrained intentions in designed tasks; they do not reveal arbitrary private thoughts.",
      transitionToNextSlide: "To see why this is becoming practical now, let’s look at the technology stack behind the experience.",
      importantConcepts: ["brain-computer interface", "non-invasive sensing", "intentional control"],
    },
    {
      id: "demo-bci-slide-2", slideNumber: 2, title: "How a Non-Invasive BCI Works", purpose: "Give the audience a simple mental model of the pipeline.",
      keyPoints: ["Sensors capture noisy brain-related signals", "Software removes artifacts and extracts features", "A trained model maps patterns to a small set of intended actions", "The interface provides feedback so user and system adapt together"],
      speakerNotes: "Walk through the loop: sense, clean, interpret, act, and provide feedback. Mention that eye movement, muscle activity, and electrical noise can contaminate measurements. The user is part of the adaptive system; performance often improves through calibration and practice.",
      transitionToNextSlide: "That pipeline has existed for years, so what has changed enough to create momentum now?",
      importantConcepts: ["signal acquisition", "artifact removal", "decoding", "closed-loop feedback"],
    },
    {
      id: "demo-bci-slide-3", slideNumber: 3, title: "Why Now", purpose: "Explain the convergence driving recent progress.",
      keyPoints: ["Better dry and wearable sensors", "Improved machine-learning methods", "Cheaper edge computation", "Growing accessibility and rehabilitation demand", "More usable consumer form factors"],
      speakerNotes: "Avoid claiming that one breakthrough solved BCI. Progress comes from convergence. Sensors are still imperfect, but setup is becoming faster. Models can use temporal and spatial patterns more effectively. Compute can run closer to the user. Product teams also understand usability and accessibility better than earlier laboratory prototypes did.",
      transitionToNextSlide: "The result is not one universal device, but several focused opportunities where the value is already understandable.",
      importantConcepts: ["technology convergence", "wearability", "machine learning", "accessibility"],
    },
    {
      id: "demo-bci-slide-4", slideNumber: 4, title: "Where Value Appears First", purpose: "Ground the vision in realistic applications.",
      keyPoints: ["Communication support for people with severe motor impairments", "Hands-free control in constrained interfaces", "Rehabilitation feedback", "Attention and workload research with careful consent", "Creative and gaming interactions as secondary markets"],
      speakerNotes: "Lead with assistive communication because the benefit can justify calibration time and lower throughput. Distinguish clinical decision support from consumer wellness claims. Explain that constrained commands such as choose left or right are much more realistic than decoding open-ended language from a casual headset.",
      transitionToNextSlide: "These opportunities are meaningful, but the limits of the signal must shape every product promise.",
      importantConcepts: ["assistive communication", "constrained control", "rehabilitation", "product-market fit"],
    },
    {
      id: "demo-bci-slide-5", slideNumber: 5, title: "The Reality Check", purpose: "Build credibility by stating technical limitations plainly.",
      keyPoints: ["Non-invasive signals are weak and noisy", "Performance varies across people and sessions", "Calibration can be burdensome", "Movement artifacts can mimic neural patterns", "Lab accuracy does not automatically become real-world reliability"],
      speakerNotes: "This is the credibility slide. Say directly that the skull and tissue blur electrical signals and that daily conditions change measurements. A model can accidentally learn eye or muscle artifacts. Metrics must include setup time, false activations, and performance across days, not only best-case laboratory accuracy.",
      transitionToNextSlide: "Technical honesty is necessary, but neural data also creates a deeper responsibility: protecting the person behind the signal.",
      importantConcepts: ["signal-to-noise ratio", "calibration", "distribution shift", "false activation"],
    },
    {
      id: "demo-bci-slide-6", slideNumber: 6, title: "Trust Must Be Designed In", purpose: "Present an actionable responsible-development framework.",
      keyPoints: ["Collect only signals needed for the feature", "Process locally when feasible", "Make recording and inference visible", "Require meaningful consent for secondary use", "Let users inspect, export, and delete their data", "Test for unequal performance across users"],
      speakerNotes: "Frame neural data as sensitive even when it cannot decode arbitrary thoughts. The risk includes future reuse, unintended inferences, and loss of agency. Recommend data minimization, clear recording indicators, local processing, revocable consent, short retention, and independent security review. Avoid treating a long terms-of-service document as meaningful consent.",
      transitionToNextSlide: "With those guardrails, we can describe a practical roadmap rather than an abstract promise.",
      importantConcepts: ["neural privacy", "data minimization", "user agency", "informed consent", "fairness"],
    },
    {
      id: "demo-bci-slide-7", slideNumber: 7, title: "A Responsible Roadmap", purpose: "End with phased next steps and a memorable thesis.",
      keyPoints: ["Start with one high-value constrained task", "Measure reliability across days and users", "Co-design with the people who depend on the system", "Expand capabilities only after trust and utility are demonstrated", "Treat agency as a product requirement"],
      speakerNotes: "Propose a phased path: first validate one intentional command in a population with a real unmet need. Then improve setup, longitudinal reliability, and error recovery. Co-design with users, clinicians, and caregivers where relevant. Close with the main thesis and then use the prepared closing script.",
      transitionToNextSlide: "There is no next slide; pause, deliver the closing, and invite questions.",
      importantConcepts: ["phased validation", "co-design", "longitudinal reliability", "responsible innovation"],
    },
  ],
  questions: [
    { id: "demo-bci-question-1", question: "Can this technology actually read thoughts?", whyTheyMightAsk: "Public discussion often describes BCI as mind reading.", suggestedAnswer: "Current non-invasive systems can classify limited patterns associated with specific tasks after calibration. They cannot reliably reveal arbitrary private thoughts. The honest framing is constrained intent recognition, not general mind reading.", keyPointToRemember: "Constrained, calibrated inference is not unrestricted thought decoding." },
    { id: "demo-bci-question-2", question: "Why use a non-invasive system if implants produce stronger signals?", whyTheyMightAsk: "They want to understand the product tradeoff.", suggestedAnswer: "Implants can provide higher-resolution signals but require surgery and clinical risk. Non-invasive systems trade signal quality for accessibility, reversibility, and broader deployment. The right choice depends on the user's need and the benefit required to justify risk.", keyPointToRemember: "The value proposition is lower risk and wider access, not equal signal quality." },
    { id: "demo-bci-question-3", question: "What is the biggest technical obstacle?", whyTheyMightAsk: "They want one concise assessment of feasibility.", suggestedAnswer: "Reliable performance across days and real-world conditions is the central challenge. Signals are weak, artifacts are common, and calibration can drift. A useful product must recover gracefully from uncertainty, not just achieve a strong laboratory average.", keyPointToRemember: "Longitudinal reliability matters more than a best-case demo." },
    { id: "demo-bci-question-4", question: "What is the first realistic commercial application?", whyTheyMightAsk: "They are evaluating market timing.", suggestedAnswer: "Focused assistive communication and constrained hands-free control are strong early candidates because even modest information throughput can create major value. Broad consumer mind-control interfaces are less mature and face a weaker benefit-to-friction ratio.", keyPointToRemember: "Start where constrained control produces outsized human value." },
    { id: "demo-bci-question-5", question: "How should neural data be regulated?", whyTheyMightAsk: "The topic raises privacy and policy concerns.", suggestedAnswer: "At minimum, neural data should receive strong sensitive-data protections: explicit purpose limitation, meaningful consent, security requirements, access and deletion rights, and restrictions on employment, insurance, or advertising use. Rules should address future inferences, not only today's capabilities.", keyPointToRemember: "Protect the person and future uses, not merely the raw file." },
    { id: "demo-bci-question-6", question: "Could the model confuse muscle movement with brain activity?", whyTheyMightAsk: "They understand that wearable measurements contain artifacts.", suggestedAnswer: "Yes. Eye and muscle activity can dominate non-invasive recordings. Responsible validation uses artifact monitoring, control tasks, sensor checks, and tests designed to prove that performance survives when those shortcuts are removed.", keyPointToRemember: "Artifact controls are essential evidence, not optional cleanup." },
    { id: "demo-bci-question-7", question: "How do you prevent unequal performance across users?", whyTheyMightAsk: "Wearables and models frequently work differently across populations.", suggestedAnswer: "Recruit diverse participants early, report performance distributions rather than one average, investigate sensor fit and physiological variation, and provide fallback interaction methods. A system should never make access depend on fitting one narrow neural profile.", keyPointToRemember: "Measure distributions and always preserve an alternative control path." },
    { id: "demo-bci-question-8", question: "What would make you stop a BCI product launch?", whyTheyMightAsk: "They want evidence that the safety principles affect decisions.", suggestedAnswer: "I would stop if false activations could cause harm, if users could not understand when data was recorded, if consent depended on coercion, or if performance failures systematically excluded groups without a fallback. Trust requirements must be launch criteria, not future improvements.", keyPointToRemember: "Safety, consent, and agency are release gates." },
  ],
};
